Localizer refactoring
mindbox-moscow/Mindbox.I18n pull request #68
Opened 2022-10-07 08:36 UTC by gkurbesov

https://github.com/mindbox-moscow/issues-framework/issues/681

2022-10-08 09:29 UTC, itsyrulnikov requested changes

2022-10-08 09:29 UTC, itsyrulnikov commented on Directory.Build.props
> +    <VersionSuffix>$(VersionTag)</VersionSuffix>
Давай переделаем так же, как и в других либах? Чтобы номер билда в минорной подставлялся

2022-10-08 09:29 UTC, itsyrulnikov commented on Mindbox.I18n.Abstractions/LocalizationTemplateParameters.cs
> +	public IReadOnlyDictionary<string, object?> Fields => _fields;
а просто гет пропертей не обойтись?

2022-10-08 09:29 UTC, itsyrulnikov commented on Mindbox.I18n.Templates/ILocalizationProvider.cs
> +internal interface ILocalizationProvider
я бы провайдер держал в реализации (Mindbox.i18n).  Он же не зависит от квоки и в теории может быть переиспользован в другом теплейте с другим шаблонизатором.

2022-10-08 09:29 UTC, itsyrulnikov commented on Mindbox.I18n.Templates/ILocalizationProvider.cs
> +internal interface ILocalizationProvider
ну и сборки бы подружил https://learn.microsoft.com/en-us/dotnet/standard/assembly/friend

2022-10-08 09:29 UTC, itsyrulnikov commented on Mindbox.I18n.Templates/LocalizationProvider.cs
> +internal class LocalizationProvider : ILocalizationProvider
тоже в реализации

2022-10-08 10:49 UTC, gkurbesov commented on Mindbox.I18n.Abstractions/LocalizationTemplateParameters.cs
> +	public IReadOnlyDictionary<string, object?> Fields => _fields;
Ну тогда можно будет изменять словарь за пределами класса - хотим ли так?

2022-10-10 08:03 UTC, itsyrulnikov requested changes

2022-10-10 08:03 UTC, itsyrulnikov commented on Mindbox.I18n.Abstractions/LocalizationTemplateParameters.cs
> +	public Dictionary<string, object?> Fields { get; } = new();
а зачем тут object? почему не string?

2022-10-10 08:03 UTC, itsyrulnikov commented on Mindbox.I18n.Abstractions/Mindbox.I18n.Abstractions.csproj
> +    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
давай лучше выпилим вообще, чтобы не смущало?

2022-10-10 08:06 UTC, gkurbesov commented on Mindbox.I18n.Abstractions/LocalizationTemplateParameters.cs
> +	public Dictionary<string, object?> Fields { get; } = new();
Все методы добавляют значения через WithFieldCore<TEntityType>(), который использовал класс из квоки `PrimitiveModelValue()`. В этот класс значения передавались как тип `object`.
Если м будем примитивные типы приводить к строке тут - это повлияет на локализацию. Как минимум отображение точек и запятых в дробных числах

2022-10-10 08:08 UTC, itsyrulnikov commented on Mindbox.I18n.Abstractions/LocalizationTemplateParameters.cs
> +	public Dictionary<string, object?> Fields { get; } = new();
звучит валидно

2022-10-10 08:11 UTC, gkurbesov commented on Mindbox.I18n.Abstractions/Mindbox.I18n.Abstractions.csproj
> +    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
Убрал

2022-10-10 08:12 UTC, itsyrulnikov approved these changes

2022-10-10 08:15 UTC, merged