Parameterization feature
mindbox-moscow/Mindbox.I18n pull request #70
Opened 2022-10-27 15:05 UTC by gkurbesov

https://github.com/mindbox-moscow/issues-framework/issues/682

2022-10-27 16:32 UTC, itsyrulnikov requested changes
А расширение локалайзера? Не хочет каждый раз сборки обновлять, бывает больно!

2022-10-27 16:37 UTC, gkurbesov commented
> А расширение локалайзера? Не хочет каждый раз сборки обновлять, бывает больно!

Ага, ещё процессе по этому пока драфт)

2022-10-28 13:31 UTC, gkurbesov commented on Mindbox.I18n.Abstractions/ILocalizer.cs
> +		LocalizationTemplateParameters? localizationTemplateParameters = null);
Решил  немного изменить название, что бы больше соответствовало его предназначению
Добавил в интерфейс и заимплементил т.к. для работы требуется ITemplateFactory, которую не удалось бы получить в методе расширения

2022-10-28 13:38 UTC, gkurbesov commented on Mindbox.I18n.Abstractions/LocalizationTemplateParameters.cs
> +	}
Воспроизвел логику объединения параметров из старой локализации [TemplateViewModelBuilder.Union()](https://github.com/mindbox-moscow/Mindbox.Framework/blob/08a0ca1877d0873dd004cf301aa8e9f978114374/Commons/Commons.Model/Model/Templates/CompositeParameters/Builders/TemplateViewModelBuilder.cs#L15)

2022-10-28 13:38 UTC, gkurbesov commented on Mindbox.I18n.Templates/Localizer.cs
> +	}
Это для тестов, что бы моки просовывать

2022-10-28 13:41 UTC, gkurbesov commented on Mindbox.I18n.Templates/Localizer.cs
> +		LocalizationTemplateParameters? localizationTemplateParameters = null)
Метод возвращает локализованную строку для указанной локали только в том случае, если она содержит параметры, и переданные параметры соответствуют тем, которые в ней находятся (согласно работе [этого кода](https://github.com/mindbox-moscow/Mindbox.Framework/blob/af8785bc39d82b97870450fdd9e94bcc8d0a4583/Commons/Commons.Model/Model/Validation/ValidationMessageSection.cs#L82))

2022-10-28 13:47 UTC, gkurbesov commented on Mindbox.I18n.Templates/TemplateExtensions.cs
> +	{
Этот метод тоже реализует логику как в старой локализации:
сверяет переданные параметры с параметрами из шаблона

2022-10-28 14:18 UTC, gizdatullin commented on Mindbox.I18n.Templates/Localizer.cs
> +		return template.Accepts(localizationParameters)
В методе ниже нет проверки. Так и должно быть?

2022-10-28 14:18 UTC, gizdatullin commented on Mindbox.I18n.Abstractions/LocalizationTemplateParameters.cs
> +	public static LocalizationTemplateParameters Union(params LocalizationTemplateParameters[] localizationTemplateParameters)
Неочевидно, чем union от concat отличается.

2022-10-28 14:18 UTC, gizdatullin commented on Mindbox.I18n.Tests/TestsInfrastucture/CompositeModelDefinitionStub.cs
> +			["firstParam"] = Mock.Of<IModelDefinition>(),
Очень сложно читать тесты, когда тестовые данные находятся в другом файле. Что думаешь? Может лучше куда-нибудь в readonly запихнем и будем всегда явно передавать.

2022-10-28 14:18 UTC, gizdatullin commented on Mindbox.I18n.Templates/Localizer.cs
> +			return null;
А точно надо null возвращать? Строка же может быть без параметров. Больше похоже на логику accept.

2022-10-28 14:19 UTC, gkurbesov commented on Mindbox.I18n.Templates/Localizer.cs
> +		LocalizationTemplateParameters? localizationTemplateParameters = null)
А у нас есть прям юзкейсы, где параметры передаются в самой строке, а потом еще через этот метод докидываются?
Ага, есть такое

2022-10-28 14:20 UTC, gizdatullin commented on Mindbox.I18n.Templates/Localizer.cs
> +		LocalizationTemplateParameters? localizationTemplateParameters = null)
Выстрел в ногу какой-то, но ок.

2022-10-28 14:21 UTC, gkurbesov commented on Mindbox.I18n.Tests/TestsInfrastucture/CompositeModelDefinitionStub.cs
> +			["firstParam"] = Mock.Of<IModelDefinition>(),
Возможно

2022-10-28 14:21 UTC, gkurbesov commented on Mindbox.I18n.Templates/Localizer.cs
> +			return null;
Точно, для поддержания старой логики

2022-10-28 14:23 UTC, gkurbesov commented on Mindbox.I18n.Templates/Localizer.cs
> +	}
В прошлой итерации к этому пришли по решению Ильи, когда отрывали публичный провайдер

2022-10-28 14:24 UTC, gkurbesov commented on Mindbox.I18n.Templates/Localizer.cs
> +		return template.Accepts(localizationParameters)
Не понял о чем именно ты?

2022-10-28 14:26 UTC, gizdatullin commented on Mindbox.I18n.Templates/Localizer.cs
> +		return template.Accepts(localizationParameters)
Я про метод ниже, который уже был. Тут можно зарезоливить, так как в фреймворке также. Я чет изначально думал, что тут какие-то улучшения делаются, а не функционал фреймворка портируется.

2022-10-28 14:30 UTC, gkurbesov commented on Mindbox.I18n.Templates/Localizer.cs
> +		return template.Accepts(localizationParameters)
Понял, проверка для того, что бы гарантировать, что все параметры были подставлены.
Если такая проверка делалась раньше - видимо это очень критично

2022-10-28 14:38 UTC, gkurbesov commented on Mindbox.I18n.Tests/TestsInfrastucture/CompositeModelDefinitionStub.cs
> +			["firstParam"] = Mock.Of<IModelDefinition>(),
Улучшил

2022-10-28 14:42 UTC, gizdatullin submitted a review, later dismissed

2022-10-31 06:11 UTC, itsyrulnikov requested changes

2022-10-31 06:11 UTC, itsyrulnikov commented on Mindbox.I18n.Abstractions/ILocalizer.cs
> +	string? TryGetParameterizedLocalizedString(
Методы TryGetParameterizedLocalizedString и GetLocalizedString должны работать одинаково и название иметь одинаковое (за исключением Try, конечно). Можно даже GetLocalizedString реализовать в интерфейсе.

2022-10-31 06:11 UTC, itsyrulnikov commented on Mindbox.I18n.Templates/Localizer.cs
> +			return null;
Тот же вопрос, зачем эта логика нужна? GetLocalizedString должен работать аналогично, нужно делать понятный апи для разработчиков

2022-10-31 06:11 UTC, itsyrulnikov commented on Mindbox.I18n.Abstractions/LocalizableString.cs
> +	public LocalizationTemplateParameters? LocalizationParameters { get; set; }
сеттер приватный должен быть

2022-10-31 08:45 UTC, gkurbesov commented on Mindbox.I18n.Templates/Localizer.cs
> +			return null;
Тут изменил https://github.com/mindbox-moscow/Mindbox.I18n/pull/70/commits/a85295b53af721a80e1735e4f7eac81aebfd8699

2022-10-31 10:18 UTC, itsyrulnikov requested changes

2022-10-31 10:18 UTC, itsyrulnikov commented on Mindbox.I18n.Templates/Localizer.cs
> +		       ?? GetTranslate(locale, localizableString);
а точно такая логика и была? если не получилось отрендерить параметры – возвращаем локализованную строку без подстановки параметров?

2022-10-31 11:09 UTC, gkurbesov commented on Mindbox.I18n.Templates/Localizer.cs
> +		       ?? GetTranslate(locale, localizableString);
поправил - там ключ возвращался в случае неудачи, но сейча только нужно решить вопрос с переносом типа исключения, который должен перехватываться, в абстракции квоки

2022-11-01 09:01 UTC, itsyrulnikov requested changes

2022-11-01 09:01 UTC, itsyrulnikov commented on Mindbox.I18n.Abstractions/Parameters/ParameterValue.cs
> +#pragma warning restore CA1040
а зачем тут прагма? почему это не интерфейс?

2022-11-01 09:35 UTC, gkurbesov commented on Mindbox.I18n.Abstractions/Parameters/ParameterValue.cs
> +#pragma warning restore CA1040
> а зачем тут прагма?

Тут забыл убрать, изначально использовал пустой интерфейс, но таким образом не работает неявное приведение, когда рекорды параметров наследуются от интерфейса:

![image](https://user-images.githubusercontent.com/39064929/199204252-cb20a894-1fd2-4ed8-a5f1-d2ad51cc0973.png)

2022-11-01 09:56 UTC, itsyrulnikov commented on Mindbox.I18n.Abstractions/Parameters/ParameterValue.cs
> +#pragma warning restore CA1040
давай хотя бы абстрактным сделаем

2022-11-01 10:00 UTC, gkurbesov commented on Mindbox.I18n.Abstractions/Parameters/ParameterValue.cs
> +#pragma warning restore CA1040
А я уже))
https://github.com/mindbox-moscow/Mindbox.I18n/pull/70/commits/8bb163c7a74b6e6a9145fd49e8776baee2878488

2022-11-01 17:21 UTC, itsyrulnikov approved these changes

2022-11-01 19:37 UTC, merged